stages:
  - build
  - deploy

variables:
  DIST_DIR: build

workflow:
  rules:
  - if: $CI_PIPELINE_SOURCE == "web"

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - $DIST_DIR/

deploy:
  stage: deploy
  script:
    - $TARGET = ""
    - >
      if ($DEPLOY_TO_PROD -eq 1) {
        $TARGET = $TARGET_PROD
      } else {
        $TARGET = $TARGET_DEV
      }

    - $HOST_ADDR, $HOST_PATH = $TARGET.Split(":")
    - ssh $HOST_ADDR "rm -f -r $HOST_PATH/*"
    - scp -r $DIST_DIR/* ${HOST_ADDR}:${HOST_PATH}
