stages:
  - build
  - deploy

variables:
  DIST_DIR: build

workflow:
  rules:
  - if: $CI_PIPELINE_SOURCE == "web"

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - $DIST_DIR/

deploy:
  stage: deploy
  script:
    - ssh $WEB_HOST "rm -f -r ~/web/*"
    - scp -r $DIST_DIR/* ${WEB_HOST}:~/web
