stages:
  - build
  - deploy

variables:
  DIST_DIR: build

workflow:
  rules:
    # You have to manually trigger a build from the GitLab website.
    - if: $CI_PIPELINE_SOURCE == "web"

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - $DIST_DIR/

deploy:
  stage: deploy
  script:
    - $TARGET = ""
    # If you trigger the build without any flag, the site will be uploaded to http://new-mxt.mxt.co.uk/.
    # If you instead use the `DEPLOY_TO_PROD` key with value `1` the site will be upladed to https://mxt.co.uk/.
    - >
      if ($DEPLOY_TO_PROD -eq 1) {
        $TARGET = $TARGET_PROD
      } else {
        $TARGET = $TARGET_DEV
      }

    - $HOST_ADDR, $HOST_PATH = $TARGET.Split(":")
    - ssh $HOST_ADDR "rm -f -r $HOST_PATH/*"
    - scp -r $DIST_DIR/* ${HOST_ADDR}:${HOST_PATH}
