import * as THREE from 'three';

// The `ambientOcclusionTextureAndHighlight` texture should have
//  - in the red channel the ambient occlusion
//  - in the green channel the highlight color
export function newDioramaMaterial(ambientOcclusionTextureAndHighlight: string) {
	const material = new THREE.ShaderMaterial({
		vertexShader: `
        out vec3 vNormalWorld;
        varying vec2 vUv;
        varying vec3 vPosition;

        void main() {
            vNormalWorld = normalize(normalMatrix * normal);
            vUv = uv;
            vPosition = position;

            vec4 modelViewPosition = modelViewMatrix * vec4(position, 1.0);
            gl_Position = projectionMatrix * modelViewPosition; 
        }
        `,
		fragmentShader: `
        uniform vec3 backgroundColor;
        uniform vec3 baseColor;
        uniform vec3 baseColorShadow;
        uniform vec3 accentColor1; // Left.
        uniform vec3 accentColor2; // Right.
        uniform vec3 accentColor3; // Up and down.
        uniform vec3 accentColor4; // Towards camera.
        uniform vec3 highlightColor;
        uniform float highlightColorFadeStart;
        uniform float highlightColorFadeEnd;
        uniform sampler2D tAmbientOcclusionAndHighlight;
        in vec3 vNormalWorld;
        varying vec2 vUv;
        varying vec3 vPosition;

        float map(float value, float min1, float max1, float min2, float max2) {
            return min2 + (value - min1) * (max2 - min2) / (max1 - min1);
        }

        float customLinearEasing(float x, float minValue, float maxValue, float startPoint, float endPoint) {
            if (x <= startPoint) {
                return minValue;
            } else if (x >= endPoint) {
                return maxValue;
            }
            
            // Calculate the slope of the linear segment.
            float slope = (maxValue - minValue) / (endPoint - startPoint);
            
            // Calculate the value using linear interpolation.
            return minValue + slope * (x - startPoint);
        }

        void main() {
            // Not sure why but the y needs to be inverted.
            vec2 uv = vec2(vUv.r, 1.0 - vUv.g);

            vec4 uvTex = texture2D(tAmbientOcclusionAndHighlight, uv);

            // A diormama mesh has a circular base. That base needs to be of the colour of the background. Above it, base colour.
            vec3 baseColor_ = mix(backgroundColor, baseColor, clamp(map(vPosition.g, 0.0001, 0.3, 0.0, 1.0), 0.0, 1.0));

            // Create the colour that will be used in the shadows generated by the ambient occlusion.
            // This colour uses as base 'accentColor4'. Then, it adds accent colours relative to the
            // surface normal.
            vec3 tintedShadowX = mix(accentColor1, accentColor2, map(vNormalWorld.x, -1.0, 1.0, 0.0, 1.0));
            vec3 tintedShadowY = accentColor3;
            vec3 tintedShadowXY = mix(tintedShadowX, tintedShadowY, 1.0 - abs(vNormalWorld.x));
            float tintedShadowZAlpha = clamp(vNormalWorld.z, 0.0, 1.0); // Negative numbers become 0 (they are 'behind' the object).
            tintedShadowZAlpha = clamp(map(tintedShadowZAlpha, 0.0, 1.0, -2.1, 1.0), 0.0, 1.0); // Make it more colorful.
            tintedShadowZAlpha = min(tintedShadowZAlpha, 0.6);
            vec3 tintedShadowZ = mix(tintedShadowXY, accentColor4, tintedShadowZAlpha);
            vec3 tintedShadow = tintedShadowZ;

            // Add 'highlightColor' to 'baseColor_'.
            vec3 baseColorWithHighlight = mix(baseColor_, highlightColor, uvTex.g);

            // Create a gradient to map 'uvTex' to. The gradient has 3 colours: 'baseColorWithHighlight', 'tintedShadow' and 'baseColorShadow'.
            vec3 finalColor = mix(tintedShadow, baseColorWithHighlight, customLinearEasing(uvTex.r, 0.2, 1.0, 0.66, 0.83));
            finalColor = mix(baseColorShadow, finalColor, customLinearEasing(uvTex.r, 0.7, 1.0, 0.1, 0.5));

            // Fade at the edge of the diorama.
            float distFromCenterHorizontal = sqrt(pow(vPosition.r, 2.0) + pow(vPosition.b, 2.0));
            float fadeColorAmount = 1.0 - clamp(map(distFromCenterHorizontal, highlightColorFadeStart, highlightColorFadeEnd, 0.0, 1.0), 0.0, 1.0);
            finalColor = mix(backgroundColor, finalColor, fadeColorAmount);
            
            gl_FragColor = vec4(finalColor, 1.0);

            #include <tonemapping_fragment>
            #include <colorspace_fragment>
        }
        `,
		uniforms: {
			backgroundColor: { value: new THREE.Color('cyan') },
			baseColor: { value: new THREE.Color('cyan') },
			baseColorShadow: { value: new THREE.Color('black') },
			accentColor1: { value: new THREE.Color('red') },
			accentColor2: { value: new THREE.Color('green') },
			accentColor3: { value: new THREE.Color('blue') },
			accentColor4: { value: new THREE.Color('blue') },
			highlightColor: { value: new THREE.Color('cyan') },
			highlightColorFadeStart: { value: 340 },
			highlightColorFadeEnd: { value: 370 },
			tAmbientOcclusionAndHighlight: {
				value: new THREE.TextureLoader().load(ambientOcclusionTextureAndHighlight)
			}
		},
		toneMapped: false // Makes the colours match the ones in the HTML.
	});

	return {
		material,
		setBackgroundColor: (value: THREE.Color) => {
			material.uniforms.backgroundColor.value = value;
		},
		setBaseColor: (value: THREE.Color) => {
			material.uniforms.baseColor.value = value;
		},
		setBaseColorShadow: (value: THREE.Color) => {
			material.uniforms.baseColorShadow.value = value;
		},
		setAccentColor1: (value: THREE.Color) => {
			material.uniforms.accentColor1.value = value;
		},
		setAccentColor2: (value: THREE.Color) => {
			material.uniforms.accentColor2.value = value;
		},
		setAccentColor3: (value: THREE.Color) => {
			material.uniforms.accentColor3.value = value;
		},
		setAccentColor4: (value: THREE.Color) => {
			material.uniforms.accentColor4.value = value;
		},
		setHighlightColor: (value: THREE.Color) => {
			material.uniforms.highlightColor.value = value;
		},
		dispose: () => {
			material.dispose();
		}
	};
}
