export const fragmentShader = `
    uniform vec3 backgroundColor;
    uniform float blendWithBackground;
    uniform vec3 baseColor;
    uniform vec3 baseColorShadow;
    uniform vec3 accentColor1; 
    uniform vec3 accentColor2; 
    uniform vec3 accentColor3;
    // in vec3 vNormal;
    in vec3 vNormalWorld;

    float map(float value, float min1, float max1, float min2, float max2) {
        return min2 + (value - min1) * (max2 - min2) / (max1 - min1);
    }

    void main() {
        // Create the colour that will be used in the shadows generated by the ambient occlusion.
        // This colour uses as base 'baseColorShadow'. Then, it adds accent colours relative to the
        // surface normal.
        vec3 tintedShadowX = mix(accentColor1, accentColor2, map(vNormalWorld.x, -1.0, 1.0, 0.0, 1.0));
        vec3 tintedShadowY = accentColor3;
        vec3 tintedShadowXY = mix(tintedShadowX, tintedShadowY, 1.0 - abs(vNormalWorld.x));
        float tintedShadowZAlpha = clamp(vNormalWorld.z, 0.0, 1.0); // Negative numbers become 0 (they are 'behind' the object).
        tintedShadowZAlpha = clamp(map(tintedShadowZAlpha, 0.0, 1.0, -2.1, 1.0), 0.0, 1.0); // Make it more colorful.
        tintedShadowZAlpha = min(tintedShadowZAlpha, 0.6);
        vec3 tintedShadowZ = mix(tintedShadowXY, baseColorShadow, tintedShadowZAlpha);

        // Map the ambient occlusion to colours: the light colour is 'baseColour' and the dark colour is 'tintedShadow'.
        vec3 finalColor = tintedShadowZ; // ...todo

        finalColor = mix(finalColor, backgroundColor, blendWithBackground);
        
        gl_FragColor = vec4(finalColor, 1.0);

        #include <tonemapping_fragment>
        #include <colorspace_fragment>
    }
`;
